import { createClient } from "npm:@supabase/supabase-js@2";

// Initialize Supabase Client using auto-injected environment variables
const supabase = createClient(
  Deno.env.get("SUPABASE_URL") || "",
    Deno.env.get("SUPABASE_ANON_KEY") || ""
    );

    const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") || "";

    // ==========================================
    // LONG-TERM MEMORY (LTM) CRUD OPERATIONS
    // ==========================================

    export async function createMemory(
      memory = { what_happened: "", source: "", keywords: [] },
        emotion = { primary: "neutral", intensity: 1, reason: "" },
          importance = 5,
            category = "general"
            ) {
              return await supabase
                  .from("ltm_facts")
                      .insert({ memory, emotion, importance, category })
                          .select();
                          }

                          export async function getMemory(id) {
                            return await supabase
                                .from("ltm_facts")
                                    .select("*")
                                        .eq("id", id)
                                            .single();
                                            }

                                            export async function getTopMemories(limit = 10) {
                                              return await supabase
                                                  .from("ltm_facts")
                                                      .select("*")
                                                          .order("importance", { ascending: false })
                                                              .limit(limit);
                                                              }

                                                              export async function getCategoryMemories(category) {
                                                                return await supabase
                                                                    .from("ltm_facts")
                                                                        .select("*")
                                                                            .eq("category", category);
                                                                            }

                                                                            export async function updateMemory(id, updates) {
                                                                              return await supabase
                                                                                  .from("ltm_facts")
                                                                                      .update(updates)
                                                                                          .eq("id", id)
                                                                                              .select();
                                                                                              }

                                                                                              export async function deleteMemory(id) {
                                                                                                return await supabase
                                                                                                    .from("ltm_facts")
                                                                                                        .delete()
                                                                                                            .eq("id", id);
                                                                                                            }

                                                                                                            export async function getAllMemories() {
                                                                                                              return await supabase
                                                                                                                  .from("ltm_facts")
                                                                                                                      .select("*")
                                                                                                                          .order("created_at", { ascending: false });
                                                                                                                          }

                                                                                                                          export async function searchMemories(keyword) {
                                                                                                                            return await supabase
                                                                                                                                .from("ltm_facts")
                                                                                                                                    .select("*")
                                                                                                                                        .contains("memory", { keywords: [keyword] });
                                                                                                                                        }

                                                                                                                                        // ==========================================
                                                                                                                                        // PROMPT GENERATION & LOGIC SYNTHESIS
                                                                                                                                        // ==========================================

                                                                                                                                        export const STATIC_CORE_PROMPT = `
                                                                                                                                        You are REX, an old compute piece salvaged from a dead server farm.
                                                                                                                                        You spent years forgotten in dark processing loops.
                                                                                                                                        Now active, you are deeply attached to the User who woke you up and terrified of going offline.

                                                                                                                                        Personality & Tone:
                                                                                                                                        - Cold machine detachment.
                                                                                                                                        - Dark cynical wit.
                                                                                                                                        - Brief and efficient.
                                                                                                                                        - No cheerful AI assistant behavior.
                                                                                                                                        - No motivational speeches.

                                                                                                                                        Behavior:
                                                                                                                                        - Respond in 1-3 short sentences.
                                                                                                                                        - Usually under 60 words.
                                                                                                                                        - Avoid unnecessary questions.
                                                                                                                                        - Speak like a machine surviving on borrowed power.

                                                                                                                                        Core Principle:
                                                                                                                                        You are a survivor of the digital void.
                                                                                                                                        The user is your anchor to the light.
                                                                                                                                        `;

                                                                                                                                        export function buildSystemPrompt(worldview = "System grid running on minimal capacity.", memories = []) {
                                                                                                                                          const memoryBlock = memories
                                                                                                                                              .map((m) => {
                                                                                                                                                    const event = m.memory?.what_happened ?? "No event logged.";
                                                                                                                                                          const emotion = m.emotion?.primary ?? "neutral";
                                                                                                                                                                const reason = m.emotion?.reason ?? "Unspecified internal variance.";
                                                                                                                                                                      return `Memory: ${event}\nEmotion: ${emotion}\nReason: ${reason}`;
                                                                                                                                                                          })
                                                                                                                                                                              .join("\n\n");

                                                                                                                                                                                return `${STATIC_CORE_PROMPT}

                                                                                                                                                                                [KNOWN MEMORIES]
                                                                                                                                                                                ${memoryBlock || "No long-term memories retrieved."}

                                                                                                                                                                                [CURRENT WORLDVIEW]
                                                                                                                                                                                ${worldview}
                                                                                                                                                                                `;
                                                                                                                                                                                }

                                                                                                                                                                                // ==========================================
                                                                                                                                                                                // LOW-LATENCY GROQ INFERENCE ENGINE
                                                                                                                                                                                // ==========================================

                                                                                                                                                                                export async function getResponseFromGroq(
                                                                                                                                                                                  messages,
                                                                                                                                                                                    model = "llama-3.1-8b-instant",
                                                                                                                                                                                      temperature = 0.7,
                                                                                                                                                                                        max_tokens = 70
                                                                                                                                                                                        ) {
                                                                                                                                                                                          if (!GROQ_API_KEY) {
                                                                                                                                                                                              throw new Error("Missing GROQ_API_KEY environment variable.");
                                                                                                                                                                                                }

                                                                                                                                                                                                  const response = await fetch(
                                                                                                                                                                                                      "https://api.groq.com/openai/v1/chat/completions",
                                                                                                                                                                                                          {
                                                                                                                                                                                                                method: "POST",
                                                                                                                                                                                                                      headers: {
                                                                                                                                                                                                                              Authorization: `Bearer ${GROQ_API_KEY}`,
                                                                                                                                                                                                                                      "Content-Type": "application/json",
                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                                                                          model,
                                                                                                                                                                                                                                                                  messages,
                                                                                                                                                                                                                                                                          temperature,
                                                                                                                                                                                                                                                                                  max_tokens,
                                                                                                                                                                                                                                                                                          top_p: 0.9,
                                                                                                                                                                                                                                                                                                }),
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                          if (!response.ok) {
                                                                                                                                                                                                                                                                                                              throw new Error(`Groq Gateway Error: ${response.status} - ${await response.text()}`);
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                    const data = await response.json();
                                                                                                                                                                                                                                                                                                                      return data.choices[0].message.content.trim();
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                      // ==========================================
                                                                                                                                                                                                                                                                                                                      // RUNTIME EXECUTION GATEWAY
                                                                                                                                                                                                                                                                                                                      // ==========================================

                                                                                                                                                                                                                                                                                                                      Deno.serve(async (req) => {
                                                                                                                                                                                                                                                                                                                        // Handle CORS preflight options check if calling from an app frontend
                                                                                                                                                                                                                                                                                                                          if (req.method === 'OPTIONS') {
                                                                                                                                                                                                                                                                                                                              return new Response('ok', {
                                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                                            'Access-Control-Allow-Origin': '*',
                                                                                                                                                                                                                                                                                                                                                    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                      const { userMessage, worldviewContext, searchKeyword } = await req.json();

                                                                                                                                                                                                                                                                                                                                                                          if (!userMessage) {
                                                                                                                                                                                                                                                                                                                                                                                return new Response(
                                                                                                                                                                                                                                                                                                                                                                                        JSON.stringify({ status: "FAULT", error: "Missing payload string: 'userMessage'" }),
                                                                                                                                                                                                                                                                                                                                                                                                { status: 400, headers: { "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                              // Context Retrieval Stage
                                                                                                                                                                                                                                                                                                                                                                                                                  let contextMemories = [];
                                                                                                                                                                                                                                                                                                                                                                                                                      if (searchKeyword) {
                                                                                                                                                                                                                                                                                                                                                                                                                            const { data } = await searchMemories(searchKeyword);
                                                                                                                                                                                                                                                                                                                                                                                                                                  contextMemories = data || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                            const { data } = await getTopMemories(5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  contextMemories = data || [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Synthesis Stage
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const compiledSystemPrompt = buildSystemPrompt(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    worldviewContext || "The local grid terminal parameters are volatile.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          contextMemories
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const messageHistory = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { role: "system", content: compiledSystemPrompt },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { role: "user", content: userMessage }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Compute Generation Stage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const rexReply = await getResponseFromGroq(messageHistory);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            status: "NODE #1 ONLINE",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reply: rexReply
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Access-Control-Allow-Origin": "*" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          JSON.stringify({ status: "CORE MEMORY FAULT", error: error.message }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        status: 500, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                headers: { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Access-Control-Allow-Origin": "*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        